name: Release Building
on:
  workflow_dispatch:
    inputs: {}
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        run: |
          xcodebuild -target yCHM -scheme yCHM -configuration Release build SYMROOT=$(pwd)/build
          rm -rf build/Release/yCHM/
          mkdir build/Release/yCHM
          cp -r build/Release/yCHM.app build/Release/yCHM/
          ln -s /Applications build/Release/yCHM/Applications
          hdiutil create build/Release/yCHM.dmg -ov -volname "yCHM" -fs HFS+ -srcfolder build/Release/yCHM/


      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: yCHM
          path: |
            build/Release/yCHM.dmg

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            build/Release/yCHM.dmg

